### ISSUE TITLE
Some issues following getting started

### ISSUE THREAD

**Issue by senoadiw** [edoburu/django-project-template#7]
Greetings,

Django ping gave this error when running migrate:
- No module named importlib

I removed django ping got it working using the develop branch: pip install -e git+https://github.com/rizumu/django-ping.git@develop#egg=django_ping-0.3b1

and then on runserver:
- Django ImportError: No module named middleware

Which is caused by django-axes removing middleware in the latest v2.0.0 update. Commenting out axes in settings/project.py fixed this and I am able to access the admin site.

Regards,

SN

**Comment by vdboor** [comment]
Thanks for reporting! These issues are now fixed in the current template.
